CREATE TABLE [dbo].[Bugs]
(
	[BugID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[AppID] INT NOT NULL,
	[UserID] INT NOT NULL,
	[BugSignOff] INT NULL,
	[BugDate] DATETIME DEFAULT GETDATE() NOT NULL,
	[BugDetails] NTEXT NULL,
	[RepSteps] NTEXT NULL,
	[FixDate] DATETIME DEFAULT GETDATE() NULL, 
    CONSTRAINT [FK_Bugs_Apps] FOREIGN KEY ([AppID]) REFERENCES [Applications]([AppID]),
	CONSTRAINT [FK_Bugs_Users] FOREIGN KEY ([UserID]) REFERENCES [Users]([UserID]),
	CONSTRAINT [FK_Bugs_BugLog] FOREIGN KEY ([BugSignOff]) REFERENCES [BugLog]([BugLogID])
)
